MODEL="Qwen/Qwen2.5-VL-3B-Instruct"
LORA_RANK=64
LORA_ALPHA=128
TARGET_MODULES="[q_proj,k_proj,v_proj,o_proj]"

# Memory — 3B, conservative to avoid OOM during checkpoint save + vLLM realloc
GPU_MEM_UTIL=0.75
PPO_MINI_BATCH=32
PPO_MICRO_BATCH=16
LOG_PROB_MICRO_BATCH=16
PARAM_OFFLOAD=False
OPTIMIZER_OFFLOAD=False

# vLLM
MAX_MODEL_LEN=12288
MAX_PROMPT_LENGTH=8192
MAX_RESPONSE_LENGTH=512
