MODEL="Qwen/Qwen2.5-VL-7B-Instruct"
LORA_RANK=64
LORA_ALPHA=128
TARGET_MODULES="[q_proj,k_proj,v_proj,o_proj]"

# Memory — 7B, same ballpark as UI-TARS-7B
GPU_MEM_UTIL=0.7
PPO_MINI_BATCH=16
PPO_MICRO_BATCH=2
LOG_PROB_MICRO_BATCH=2
PARAM_OFFLOAD=False
OPTIMIZER_OFFLOAD=False
