MODEL="LZXzju/Qwen2.5-VL-3B-UI-R1"
LORA_RANK=64
LORA_ALPHA=128
# UI-R1-3B is based on Qwen2.5-VL-3B — same architecture
TARGET_MODULES="[q_proj,k_proj,v_proj,o_proj]"

# Memory — 3B, generous headroom
GPU_MEM_UTIL=0.85
PPO_MINI_BATCH=32
PPO_MICRO_BATCH=32
LOG_PROB_MICRO_BATCH=32
PARAM_OFFLOAD=False
OPTIMIZER_OFFLOAD=False

# vLLM
MAX_MODEL_LEN=16384
MAX_PROMPT_LENGTH=8192
MAX_RESPONSE_LENGTH=512
