MODEL="bytedance-research/UI-TARS-7B-SFT"
LORA_RANK=64
LORA_ALPHA=128
TARGET_MODULES="[q_proj,k_proj,v_proj,o_proj]"

# Memory — H200 141G, colocate mode
GPU_MEM_UTIL=0.6
PPO_MINI_BATCH=16
PPO_MICRO_BATCH=16
LOG_PROB_MICRO_BATCH=16
PARAM_OFFLOAD=False
OPTIMIZER_OFFLOAD=False
